DIAG(["lex"], lex_null_in_string, Warning, "null character(s) preserved in string literal")
DIAG(["lex"], lex_null_in_char, Warning, "null character(s) preserved in character literal")
DIAG(["lex", "nested-block-comments"], lex_nested_block_comment, Warning, "Nested block comment")
DIAG(["lex"], lex_escaped_newline_bock_comment_end, Warning, "escaped newline between -} at block comment end")
DIAG(["lex"], lex_unterminated_string, Error, "missing terminating \" character")
DIAG(["lex"], lex_unterminated_char, Error, "missing terminating ' character")
DIAG(["lex"], cpp_unexpected_escaped_newline, Warning, "escaped newline outside of a preprocessor directive");
DIAG(["cpp"], cpp_pragma_once_in_main_file, Warning, "#pragma once in main file")
DIAG(["cpp"], cpp_include_next_in_main_file, Warning, "#include_next in main file")
DIAG(["cpp"], cpp_pragma_system_header_in_main_file, Warning, "#pragma system_header ignored in main file")
DIAGS(["cpp"], cpp_out_of_date_dependency, Warning, "current file is older than dependency" ++ show a, a, FilePath)
DIAG(["cpp", "unused-macros", "unused"], cpp_macro_not_used, Warning, "macro not used")
DIAG(["cpp"], cpp_expr_overflow, Warning, "integer overflow in preprocessing expression")
DIAG(["monad"], monad_mzero, Error, "unhandled mzero")
DIAG(["monad"], monad_fail, Error, "unhandled monad fail: " ++ show a, a, String)
